name: Build PulseOS Gaming ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Raw GSI File
      run: |
        echo "=== СКАЧИВАНИЕ PULSEOS ==="
        wget -q "https://github.com" -O PulseOS-Android11-Pine.img.xz

    - name: Upload Clean Image
      uses: actions/upload-artifact@v4
      with:
        name: PulseOS-With-PlayMarket
        path: PulseOS-Android11-Pine.img.xz
